name: EventWorld
author: Kiro47
version: 0.1
main: com.chosencraft.www.eventworld.EventWorldMain
description: Plugin to support and create the event world for ChosenCraft SMP

commands:
  eventworld:
    usage: /<command>
    description: Handles configuratory aspects of the plugin